---
- name: Stop OpenShift VM
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Start VirtualMachine
      ansible.builtin.uri:
        url: "{{ api_endpoint }}/apis/subresources.kubevirt.io/v1/namespaces/{{ vm_namespace }}/virtualmachines/{{ vm_name }}/stop"
        method: PUT
        headers:
          Authorization: "Bearer {{ cso_token }}"
          Content-Type: "application/json"
        validate_certs: false
        return_content: true
        status_code:
          - 200
          - 202
          - 204
      register: vm_stop_result

    - name: Show stop result
      ansible.builtin.debug:
        var: vm_stop_result
