---
- name: Stop OpenShift VM
  hosts: localhost
  gather_facts: false
  vars:
    vm_namespace: default
    vm_name: dummy-name

  tasks:     
    - name: Stop VirtualMachine
      ansible.builtin.uri:
        url: "{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}/apis/subresources.kubevirt.io/v1/namespaces/{{ vm_namespace }}/virtualmachines/{{ vm_name }}/stop"
        method: PUT
        headers:
          Authorization: "Bearer {{ lookup('ansible.builtin.env', 'K8S_AUTH_API_KEY') }}"
          Content-Type: "application/json"
        validate_certs: false
        return_content: true
        status_code:
          - 200
          - 202
          - 204
      register: vm_stop_result

    - name: Show stop result
      ansible.builtin.debug:
        var: vm_stop_result
